spring:
  security:
    user:
      name: admin
      password: password
    oauth2:
      client:
        registration:
          login-client:
            client-id: login-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - user.read
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/login-client
        provider:
          login-client:
            issuer-uri: http://127.0.0.1:8082

management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
debug: true