spring:
  cloud:
    gateway:
      routes:
        - id: resource-server
          uri: http://localhost:8083
          predicates:
            - Path=/user, /v3/api-docs/**, /swagger-ui/**
          filters:
            - TokenRelay=
        - id: resource-server1
          uri: http://localhost:8083
          predicates:
            - Path=/user1
          filters:
            - TokenRelay=
  security:
    user:
      name: admin
      password: password
    oauth2:
      client:
        registration:
          login-client:
            client-id: login-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - user.read
            redirect-uri: http://localhost:8080/login/oauth2/code/login-client
        provider:
          login-client:
            issuer-uri: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    gateway:
      enabled: true