spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<path>.*), /$\{path}
            - TokenRelay=
        - id: openapi
          uri: http://localhost:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

  security:
    user:
      name: admin
      password: password
    oauth2:
      client:
        registration:
          login-client:
            client-id: login-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - user.read
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/login-client
        provider:
          login-client:
            issuer-uri: http://127.0.0.1:8082

springdoc:
  swagger-ui:
    urls:
      - name: customer
        url: /v3/api-docs/customer

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    gateway:
      enabled: true