spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://customer-service:8083
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<path>.*), /$\{path}
        - id: order-service
          uri: http://order-service:8084
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://api-gateway:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      default-filters:
        - TokenRelay=

  security:
    user:
      name: admin
      password: password
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:8082/oauth2/jwks
          issuer-uri: http://auth-server:8082
      client:
        registration:
          login-client:
            client-id: login-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - user.read
              - user.admin
            redirect-uri: http://api-gateway:8080/login/oauth2/code/login-client
        provider:
          login-client:
            issuer-uri: http://auth-server:8082

springdoc:
  swagger-ui:
    oauth:
      clientId: login-client
      clientSecret: secret
    urls:
      - name: customer
        url: /v3/api-docs/customer
      - name: order
        url: /v3/api-docs/order

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: TRACE